version: 2.1

orbs:
  terraform: innovationnorway/terraform@dev:0.1.0

workflows:

  terraform:
    jobs:

      - terraform/fmt:
          filters:
            branches:
              ignore:
                - master

      - terraform/validate:
          requires:
            - terraform/fmt
          filters:
            branches:
              ignore:
                - master

      - terraform/plan:
          requires:
            - terraform/validate
          filters:
            branches:
              ignore:
                - master
                
      - terraform/apply:
          filters:
            branches:
              only:
                - master
